[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["python"]

[deploy]
startCommand = "python -m uvicorn concordance_api:app --host 0.0.0.0 --port $PORT"

[env]
PORT = "8000"
PYTHONPATH = "."